### ISSUE TITLE
The term 'firebase-config-sync' is not recognized

### ISSUE THREAD

**Issue by DavidWeiss2** [entur/firebase-config-sync#18]
![image](https://user-images.githubusercontent.com/12801099/131250204-13017960-f533-477b-8d3e-bc2eb1704ab2.png)

Windows 11 machine.
When I install the package globally, it perfectly runs.

**Comment by draperunner** [comment]
Hi! I see how the README can be confusing about this. But this is normal npm behavior. Using it globally is OK, but generally it is advised to install it locally so that all collaborators on the project are using the same version. 

I would suggest that you either create a script in your package.json, which uses the local package:
```
"scripts": {
    "get-config": "firebase-config-sync get --sort",
}
```
You can then run this with `npm run get-config`.

Or, simply use `npx`, which will use your global installation (if any) or download the latest version and run it once:

```
npx firebase-config-sync get --sort
```

**Comment by DavidWeiss2** [comment]
I will try this.
Thanks.
